# Generated by Django 4.0.5 on 2022-06-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
