# Generated by Django 4.2.23 on 2025-09-03 23:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('pinecone_index_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('indexing', 'Indexing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pages_crawled', models.IntegerField(default=0)),
                ('vectors_created', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('crawled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ragbot.websiteproject')),
            ],
            options={
                'ordering': ['-crawled_at'],
                'unique_together': {('project', 'url')},
            },
        ),
    ]
